# ç”¨æˆ·ä¿¡æ¯
user:
  name: ä¸‰ç”Ÿæœ‰å¹¸
  first_name: #ä¸‰ç”Ÿ
  last_name: #æœ‰å¹¸
  email: 1358918259@qq.com
  domain: https://github.com/fuhangyl
  avatar: /images/avatar.jpg
  describe: é†’ï¼Œäº¦åœ¨äººé—´ï¼›æ¢¦ï¼Œäº¦åœ¨äººé—´ã€‚
  ruleText: <br/>æš‚ä¸æ¥å—ä¸ªäººåšå®¢ä»¥å¤–çš„å‹é“¾ç”³è¯·ï¼Œç¡®ä¿æ‚¨çš„ç½‘ç«™å†…å®¹ç§¯æå‘ä¸Šï¼Œæ–‡ç« è‡³å°‘30ç¯‡ï¼ŒåŸåˆ›70%ä»¥ä¸Šï¼Œéƒ¨ç½²HTTPSã€‚

# å›¾æ ‡
favicon:
  logo: ''
  #logo: favicon-32x32.png
  icon16: /images/favicon.png
  icon32: /images/favicon.png
  appleTouchIcon: /images/favicon.png
  webmanifest: /site.webmanifest
  visibilitychange: true

# å¤´éƒ¨èœå•
top_bars:
  - title: menu.home
    url: /
  - title: menu.archives
    url: /archives/
#  - title: menu.links
#    url: /links/
#  - title: æ ‘æ´
#    url: /comment/
#  - title: menu.projects
#    url: /projects/
#  - title: menu.about
#    url: /about/

# æ¨ªå¹…é…ç½®
banner:
  default:
    type: video
    bgurl: //cdn.moji.com/websrc/video/autumn20190924.mp4
  index:
    type: video
    bgurl: //cdn.moji.com/websrc/video/autumn20190924.mp4
    bannerTitle: æ ‘æ·±æ—¶è§é¹¿ï¼Œ<br>æºªåˆä¸é—»é’Ÿã€‚
    bannerText: Hi my new friend!
  archive:
    type: video
    bgurl: //cdn.moji.com/websrc/video/autumn20190924.mp4
  links:
    type: video
    bgurl: //cdn.moji.com/websrc/video/autumn20190924.mp4
  about:
    type: video
    bgurl: //cdn.moji.com/websrc/video/autumn20190924.mp4

# ä¾§æ 
sidebar:
  typedTextPrefix: I`m
  typedText: [ 'Web Developer' ]
  info: 
    - key: èŒä¸š
      val: Web å‰ç«¯
    - key: èŒä½
      val: ğŸ†é¦–å¸­æ‘¸é±¼å®˜
    - key: ä»‹ç»
      val: è¶ŠåŠªåŠ›ï¼Œè¶Šå¹¸è¿
  social:
    - icon: icon-github
      url: https://github.com/fuhangyl
      name: Github
    - icon: icon-rss
      url: atom.xml
      name: RSS
#    - icon: icon-gitee
#      url: https://gitee.com/ml13
#      name: Gitee
#    - icon: icon-weibo
#      url: https://weibo.com/u/5022481764
#      name: Weibo
    
# é¡µå°¾
footer:
  # Hexo link (Powered by Hexo).
  powered:
    enable: false
  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # https://beian.miit.gov.cn/
  beian:
    enable: false
    icp: 
  # Copyright date
  copyrightYear: 2019
  # 
  live_time:
    enable: false
    prefix: footer.tips
    start_time: 1/29/2024 17:00:00 #è®¡æ—¶å¼€å§‹æ—¶é—´
  #
  custom_text: ç«¹å¤–æ¡ƒèŠ±ä¸‰ä¸¤åªï¼Œæ˜¥æ±Ÿæ°´æš–é¸­å…ˆåƒ

# å¼€å¯ Service Worker
sw: true

# rss åœ°å€
rss: atom.xml

# ç½‘é¡µè®¿é—®ç»Ÿè®¡
#webAnalytics:
#  enable: true
#  baidu: bbad9d8e1fd8e044d365c2ce0d114c73

cover:
  type: date

# æŸ¥è¯¢
search:
  enable: true
  type: local
  preload: true
  trigger: auto

# æèµ 
#reward:
#  enable: true
#  methods:
#    - name: å¾®ä¿¡
#      path: /images/reward/wx_pay.jpg
#    - name: æ”¯ä»˜å®
#      path: /images/reward/alipay.jpg
#    - name: QQ
#      path: /images/reward/qq_pay.jpg

# å½’æ¡£é¡µ
archive:
  type: more

# ä¸»é¢˜
theme: 
  switch: false 
  default: auto

# ç‰ˆæƒä¿¡æ¯
creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: false

swup: true

toc:
  enable: true

assets:
  third_party_provider: https://npm.elemecdn.com
  plugin:
    twikoo: https://npm.elemecdn.com/twikoo@1.6.11/dist/twikoo.all.min.js
  icons: 
    type: symbol 
    css:
    js: //at.alicdn.com/t/c/font_3637590_i4hyyea14ur.js

icons:
  # ä¸»é¢˜åˆ‡æ¢å›¾æ ‡
  sun: icon-sun
  moon: icon-moon
  # é¦–é¡µè§†é¢‘æ’­æ”¾
  play: icon-yunhang
  # é‚®ç®±
  email: icon-email
  # åˆ†ç±»è¿›å…¥å›¾æ ‡
  next: icon-arrow-right
  # æ–‡ç« è¯¦æƒ… æ—¥æœŸ
  calendar: icon-rili
  # æ–‡ç« è¯¦æƒ… æ—¶é—´
  clock: icon-shijian
  # æ–‡ç« è¯¦æƒ… ä½œè€…
  user: icon-yonghu
  # è¿”å›é¡¶éƒ¨ v1.1.3+
  back_top: icon-backtop
  # æŸ¥è¯¢ v1.1.5+
  search: icon-chaxun
  # å…³é—­ v1.1.5+
  close: icon-guanbi
  # æ‰“èµ v1.1.7+
  reward: icon-qiandai
  # ç”¨æˆ·ä¿¡æ¯å’Œæ–‡ç« ç›®å½•åˆ‡æ¢ v1.2.10+
  user_tag: icon-yonghu1
  toc_tag: icon-liebiao
  # å³ä¸‹è§’å›ºå®šæŒ‰é’® v1.2.11+
  read: icon-yuedu
  arrows: icon-arrows-h
  # ä»£ç å—
  double_arrows: icon-angle-double-down
  copy: icon-copy

highlight:
  enable: true
  theme: true #
  title: mac # mac | default
  copy: true # copy button
  lang: true # show the code language
  height_limit: 200 # unit: px

prismjs:
  enable: false

post_pagination: 
  enable: true 
  type: small # large || small

layout:
  fixed_btn: async/fixed-btn
  header_search: async/empty
  post_card: async/post-card

datetime_foramt:
  post_card:
    date: YY/MM/DD
    time: HH:mm
  post_info:
    date: YY/MM/DD
    time: HH:mm
  archive:
    date: YY/MM/DD
    time: HH:mm

comment:
  twikoo:
    enable: false
    envId: